ci format be check

diff --git a/.github/workflows/backend-ci.yml b/.github/workflows/backend-ci.yml
--- a/.github/workflows/backend-ci.yml
+++ b/.github/workflows/backend-ci.yml
@@ -30,6 +30,13 @@ jobs:
         with:
           dotnet-version: '7.0.x'
 
+      - name: Check format
+        run: |
+          if ! dotnet format  --verify-no-changes -v diag ./HouseFinder360.sln; then
+            echo "Error: Code formatting issues found. Did you forget to run 'dotnet format ./HouseFinder360.sln'?"
+            exit 1
+          fi
+
       - name: Restore dependencies
         run: dotnet restore
 
